---
- name: amazon_efs_utils
  src: https://github.com/cisagov/ansible-role-amazon-efs-utils
- name: automated_security_updates
  src: https://github.com/cisagov/ansible-role-automated-security-updates
- name: banner
  src: https://github.com/cisagov/ansible-role-banner
- name: chrony_aws
  src: https://github.com/cisagov/ansible-role-chrony-aws
- name: clamav
  src: https://github.com/cisagov/ansible-role-clamav
- name: cloudwatch_agent
  src: https://github.com/cisagov/ansible-role-cloudwatch-agent
- name: harden
  src: https://github.com/cisagov/ansible-role-hardening-2
- name: htop
  src: https://github.com/cisagov/ansible-role-htop
- name: nvme
  src: https://github.com/cisagov/ansible-role-nvme
- name: persist_journald
  src: https://github.com/cisagov/ansible-role-persist-journald
- name: pip
  src: https://github.com/cisagov/ansible-role-pip
- name: python
  src: https://github.com/cisagov/ansible-role-python
- name: remove_python2
  src: https://github.com/cisagov/ansible-role-remove-python2
- name: systemd_resolved
  src: https://github.com/cisagov/ansible-role-systemd-resolved
- name: ufw
  src: https://github.com/cisagov/ansible-role-ufw
- name: upgrade
  src: https://github.com/cisagov/ansible-role-upgrade
